### ISSUE TITLE
Fix DB migration error in postgresql 12.*

### ISSUE THREAD

**Issue by sayanarijit** [niteoweb/pyramid-realworld-example-app#86]
This happens in postgres 12.*

```
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 The above exception was the direct cause of the following exception:
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 Traceback (most recent call last):
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/bin/alembic", line 11, in <module>
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     load_entry_point('alembic==1.4.0', 'console_scripts', 'alembic')()
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/config.py", line 577, in main
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     CommandLine(prog=prog).main(argv=argv)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/config.py", line 571, in main
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     self.run_cmd(cfg, options)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/config.py", line 548, in run_cmd
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     fn(
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     script.run_env()
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     util.load_python_file(self.dir, "env.py")
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     module = load_module_py(module_id, path)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/util/compat.py", line 173, in load_module_py
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     spec.loader.exec_module(module)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/src/conduit/migrations/env.py", line 62, in <module>
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     run_migrations_online()
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/src/conduit/migrations/env.py", line 56, in run_migrations_online
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     context.run_migrations()
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "<string>", line 8, in run_migrations
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     self.get_context().run_migrations(**kw)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     step.migration_fn(**kw)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/src/conduit/migrations/versions/72a996e5a6ca_tags.py", line 21, in upgrade
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     op.create_table(
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "<string>", line 8, in create_table
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "<string>", line 3, in create_table
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/operations/ops.py", line 1250, in create_table
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     return operations.invoke(op)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/operations/base.py", line 374, in invoke
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     return fn(self, operation)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 101, in create_table
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     operations.impl.create_table(table)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/ddl/impl.py", line 258, in create_table
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     self._exec(schema.CreateTable(table))
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/alembic/ddl/impl.py", line 140, in _exec
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     return conn.execute(construct, *multiparams, **params)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     return meth(self, multiparams, params)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     return connection._execute_ddl(self, multiparams, params)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1039, in _execute_ddl
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     ret = self._execute_context(
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     self._handle_dbapi_exception(
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     util.raise_from_cause(sqlalchemy_exception, exc_info)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     reraise(type(exception), exception, tb=exc_tb, cause=cause)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     raise value.with_traceback(tb)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     self.dialect.do_execute(
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123   File "/app/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123     cursor.execute(statement, parameters)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function gen_random_uuid() does not exist
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 LINE 3:  id UUID DEFAULT gen_random_uuid() NOT NULL, 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123                          ^
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 [SQL: 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 CREATE TABLE tags (
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 	id UUID DEFAULT gen_random_uuid() NOT NULL, 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 	name VARCHAR NOT NULL, 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 	CONSTRAINT pk_tags PRIMARY KEY (id)
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 )
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 ]
Feb 27 06:02:12 pyramid-real-migrate-mi-vqtfe8 app/release.3123 (Background on this error at: http://sqlalche.me/e/f405)
Feb 27 06:02:13 pyramid-real-migrate-mi-vqtfe8 app/release.3123 Sentry is attempting to send 1 pending error messages
Feb 27 06:02:13 pyramid-real-migrate-mi-vqtfe8 app/release.3123 Waiting up to 10 seconds
Feb 27 06:02:13 pyramid-real-migrate-mi-vqtfe8 app/release.3123 Press Ctrl-C to quit
Feb 27 06:02:13 pyramid-real-migrate-mi-vqtfe8 app/release.3123 Database migrations failed!
```

Then upgrade postgres to the latest version (Available versions are 9.5, 9.6, 10, 11, 12 (the default is 12)).

- [ ] Local development DB is upgraded
- [ ] Review app DB is upgraded
- [ ] Production DB is upgraded

**Comment by sayanarijit** [comment]
Nope.. it's not postgres version related. Neither `psycopg2-binary`, `pyramid-deferred-sqla`
nor `zope.sqlalchemy`.

**Comment by sayanarijit** [comment]
Nope.. it's not postgres version related. Neither `psycopg2-binary`, `pyramid-deferred-sqla`
nor `zope.sqlalchemy`.

**Comment by sayanarijit** [comment]
Found ans in https://dba.stackexchange.com/questions/146135/psql-9-5-gen-random-uuid-not-working. Need to CREATE EXTENSION pgcrypto;

**Comment by sayanarijit** [comment]
Fixed in https://github.com/niteoweb/pyramid-realworld-example-app/pull/84
